website/dashboard/urls.py
from django.urls import path
from . import views
# from django.contrib.auth import views as auth_views

app_name = 'dashboard'

urlpatterns = [
    path('', views.home, name='home'),
    path('orders/', views.OrderListView.as_view(), name='orders'),
    path('order/<orderId>/', views.OrderProductsListView.as_view(), name='orderAdmin'),
    path('products/', views.ProductListView.as_view(), name='product-list'),
    path('create/', views.ProductCreateView.as_view(), name='product-create'),
]

website/shop/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from user import forms as user_forms

app_name = 'shop'

urlpatterns = [
    path('', views.home, name='home'),
    path('faq/', views.faq, name='faq'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('products/', views.ProductListView.as_view(), name='products'),
    path('product/<slug>/', views.ItemDetailView.as_view(), name='product'),
    path('orders/', views.OrderListView.as_view(), name='orders'),
    path('order/<orderId>/', views.OrderProductsListView.as_view(), name='order'),
    path('cart/', views.cart, name='cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('order_complete/', views.order_complete, name='order_complete'),
    path('add_to_cart/', views.addToCart, name='add_to_cart'),
    path('move_cart/', views.moveItemCarts, name='move_cart'),
    path('process_order/', views.processOrder, name='process_order'),
    path('guest/', auth_views.LoginView.as_view(template_name="shop/guestUserLogin.html", authentication_form=user_forms.UserLoginForm),name='guest'),
    path('shipping_update/', views.shipping_update, name='shipping_update'),
    path('order_confirmation/', views.confirmation, name='order_confirmation'),
    path('profile/', views.profile, name='profile'),
    path('regulamin/', views.regulamin, name='regulamin'),
]

website/website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from user import views as user_views
from user import forms as user_forms

urlpatterns = [
    path('', include('shop.urls', namespace="shop")),
    path('dashboard/', include('dashboard.urls', namespace="dashboard")),
    path('admin/', admin.site.urls),
    path('signup/', user_views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name="user/login.html", authentication_form=user_forms.UserLoginForm),name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='user/logout.html'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='user/password_reset.html', form_class=user_forms.UserPasswordResetForm), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='user/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='user/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='user/password_reset_complete.html'), name='password_reset_complete'),
    path('reset/<uidb64>/<token>/',
         user_views.activate, name='activate'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

website/dashboard/models.py
from django.db import models

# Create your models here.

website/dashboard/views.py
from django.shortcuts import render
from shop.models import Order, OrderItem, Customer, Product, Category
from datetime import date
from django.utils import timezone
from datetime import datetime
import pytz
from django.contrib.auth.decorators import user_passes_test
from django.views.generic import ListView, CreateView, DeleteView
# Create your views here.

@user_passes_test(lambda u: u.is_superuser)
def home(request):
    today = datetime.now()
    daily = Order.objects.filter(date_ordered = timezone.localtime(timezone.now()).date(), complete=True)
    dailyOrderCounter = daily.count()
    MonthlyOrderCounter = Order.objects.filter(date_ordered__month = timezone.localtime(timezone.now()).date().month, date_ordered__year = timezone.localtime(timezone.now()).date().year, complete=True).count()
    dailyIncome = 0
    for income in daily:
        dailyIncome += income.get_cart_total_brutto

    print(dailyIncome)
    # print (dailyOrderCounter)
    # print (timezone.localtime(timezone.now()).date())
    # print(timezone.localtime(timezone.now()).date().month)
    context = {"dailyOrderCounter": dailyOrderCounter, "MonthlyOrderCounter": MonthlyOrderCounter, "dailyIncome": dailyIncome, "orders": daily}
    return render(request, 'dashboard/home.html', context)


class OrderListView(ListView):
    model = Order
    template_name = "dashboard/orders.html"
    paginate_by = 10

    def get_queryset(self, *args, **kwargs):
        queryset = Order.objects.order_by('-date_ordered')
        print(queryset)
        return queryset


class OrderProductsListView(ListView):
    model = OrderItem
    template_name = "dashboard/order.html"

    def get_context_data(self, *args, **kwargs):

        try:
            data = cartData(self.request)
            counterCartItems = data['counterCartItems']
            cartItems = data['cartItems']
        except:
            counterCartItems = 0

        orderId = self.kwargs['orderId']
        order = Order.objects.get(id=orderId)
        orderItems = OrderItem.objects.filter(order=order)
        context = {'order': order, 'items': orderItems}
        return context


class ProductListView(ListView):
    model = Product
    template_name = "dashboard/products.html"
    paginate_by = 10
    ordering = 'release_date'

class ProductCreateView(CreateView):
    model = Product
    fields = ['title', 'category', 'price', 'pack', 'discount', 'size', 'slug', 'description', 'image1', 'image2', 'image3']
    template_name = "dashboard/product_form.html"

class ProductDeleteView(DeleteView):
    model = Product

# class CategoryListView(ListView):
#     model = Category
#     template_name = "dashboard/categories.html"
#     paginte_by = 20
#     ordering = 'release_date'
#
# class CategoryCreateView(CreateView):
#     model = Category
#     fields = ['title', 'category', 'price', 'pack', 'discount', 'size', 'slug', 'description', 'image1', 'image2', 'image3']
#     template_name = "dashboard/category_form.html"
#
# class CategoryDeleteView(DeleteView):
#     model = Category

website/dashboard/templates/dashboard/dashboard-base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Dashboard-WolkaModa</title>
    <link rel="stylesheet" href="{% static 'shop/assets/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'shop/assets/fonts/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'shop/assets/fonts/ionicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'shop/assets/css/Brands.css' %}">
    <link rel="stylesheet" href="{% static 'shop/assets/css/Footer-Dark.css' %}">
    <link rel="stylesheet" href="{% static 'shop/assets/css/Highlight-Clean.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/3.3.1/css/swiper.min.css">
    <link rel="stylesheet" href="{% static 'shop/assets/css/Navigation-with-Search.css' %}">
    <link rel="stylesheet" href="{% static 'shop/assets/css/Newsletter-Subscription-Form.css' %}">
    <link rel="stylesheet" href="{% static 'shop/assets/css/Simple-Slider.css' %}">
    <link rel="stylesheet" href="{% static 'shop/assets/css/card.css' %}">
    <link rel="stylesheet" href="{% static 'shop/assets/css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'shop/assets/css/main.css' %}">

    <style>
        body {
          font-family: "Lato", sans-serif;
        }
        .sidebar {
          height: 100%;
          width: 0;
          position: fixed;
          z-index: 1;
          top: 0;
          left: 0;
          background-color: #111;
          overflow-x: hidden;
          transition: 0.5s;
          padding-top: 60px;
        }

        .sidebar a {
          padding: 8px 8px 8px 32px;
          text-decoration: none;
          font-size: 25px;
          color: #818181;
          display: block;
          transition: 0.3s;
        }

        .sidebar a:hover {
          color: #f1f1f1;
        }

        .sidebar .closebtn {
          position: absolute;
          top: 0;
          right: 25px;
          font-size: 36px;
          margin-left: 50px;
        }

        .content {
            padding: 10px 15px;
        }

        .openbtn {
          font-size: 20px;
          cursor: pointer;
          background-color: #111;
          color: white;
          padding: 10px 15px;
          border: none;
        }

        .openbtn:hover {
          background-color: #444;
        }

        #main {
          transition: margin-left .5s;
          padding: 16px;
        }

        /* On smaller screens, where height is less than 450px, change the style of the sidenav (less padding and a smaller font size) */
        @media screen and (max-height: 450px) {
          .sidebar {padding-top: 15px;}
          .sidebar a {font-size: 18px;}
        }
    </style>
</head>

<body>
    <div id="mySidebar" class="sidebar">
      <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">×</a>
      <a href="{% url 'dashboard:home' %}">Home</a>
      <a href="{% url 'dashboard:orders' %}">Zamówienia</a>
      <a href="{% url 'dashboard:product-list' %}">Produkty</a>
      <a href="/admin/shop/category/">Kategorie</a>
      <a href="{% url 'shop:home' %}">Twoja Strona</a>
      <a href="{% url 'logout' %}">Wyloguj</a>
    </div>


    <div id="main">
        <button class="openbtn" onclick="openNav()">☰ Open Sidebar</button>
    </div>

    {% block content %}
    {% endblock %}

    <br />
    <center>
        <div class="page-btn">
            {% if is_paginated %}
                    {% if page_obj.has_previous %}
                        <a href='page={{page_obj.previous_page_number}}'><span>&#10094;</span></a>
                    {% endif %}
                    {% for num in page_obj.paginator.page_range %}
                        {% if page_obj.number == num %}
                            <a href="page={{num}}"><span>{{ num }}</span></a>
                        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3'  %}
                            <a href='page={{num}}'><span>{{ num }}</span></a>
                        {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                        <a href='page={{page_obj.next_page_number}}'><span>&#10095;</span></a>
                    {% endif %}
            {% endif %}
        </div>
    </center>




</body>

<script>
function openNav() {
  document.getElementById("mySidebar").style.width = "250px";
  document.getElementById("main").style.marginLeft = "250px";
}

function closeNav() {
  document.getElementById("mySidebar").style.width = "0";
  document.getElementById("main").style.marginLeft= "0";
}
</script>
<!-- <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script> -->
</html>
<body>

website/dashboard/templates/dashboard/home.html
{% extends "dashboard/dashboard-base.html" %}
{% block content %}
{% load static %}
<div class="container">
    <div class="my-4">
        <h1><strong>Home</strong></h1>
        <h2> Cześć {{request.user.customer.name}}!</h2>
    </div>
    <div>
        <h3>Ogólne Informacje</h3>

        <p>Liczba Zamówień w dniu dzisiejszym: {{dailyOrderCounter}}</p>
        <p>Dzisiejszy dochód: {{ dailyIncome|floatformat:2 }} PLN </p>
        <p>Liczba Zamówień w tym miesiącu: {{MonthlyOrderCounter}}</p>
    </div>
</div>
{% endblock %}

website/dashboard/templates/dashboard/order.html
{% extends 'dashboard/dashboard-base.html' %}
{% load static %}
{% block content %}

<div class="small-container">
    <h1>Informacje o zamówieniu: </h1>
	<div class="row">
		<div class="col-2">
            <div class="card">
			<p style="font-size:22px">Dane klienta</p>
            <p>Imię i nazwisko: </p>
            <p>Firma: </p>
            <p>NIP: </p>
            <br />
            <br />
            </div>
		</div>
		<div class="col-2">
            <div class="card">
			<p style="font-size:22px">Adres Dostawy</p>
            <p>Ulica: </p>
            <p>Kod pocztowy: </p>
            <p>Miejscowość: </p>
            <p>Miasto: </p>
            <p>Kraj: </p>
            </div>
		</div>
	</div>
	<table>
		<tr>
			<th>Produkt:</th>
			<th>Ilość:</th>
			<th>W sumie:</th>
		</tr>
		{% for item in items %}
		<tr style="border-bottom: 1px solid lightgrey;">
			<td>
				<a href="{{ item.product.get_absolute_url }}"><img src="{{ item.product.image1.url }}" ></a>
				<div>
					<p>{{item.product.title}}</p>
					<small>Cena: {{item.product.price}}PLN</small>
				</div>
			</td>
			<td>
				<p>{{item.quantity}}</p>
			</td>
			<td>
				<div class="column">
					<p>Cena netto: {{item.get_total|floatformat:2}} PLN</p>
					<p>Vat: {{item.get_vat|floatformat:2}} PLN</p>
					<p>Cena brutto: {{item.get_brutto|floatformat:2}} PLN</p>
				</div>
			</td>
		</tr>
		{% endfor %}
		</table>

	<div class="total-price" style="margin-top: 20px">
		<table>
			<tr>
				<td>Razem</td>
				<td>{{order.get_cart_total}} PLN</td>
			</tr>
			<tr>
				<td>Podatek</td>
				<td>{{order.get_cart_total_vat|floatformat:2}} PLN</td>
			</tr>
			<tr>
				<td>W sumie</td>
				<td>{{order.get_cart_total_brutto|floatformat:2}} PLN</td>
			</tr>
		</table>
	</div>
</div>

{% endblock content %}

website/dashboard/templates/dashboard/orders.html
{% extends "dashboard/dashboard-base.html" %}
{% block content %}
{% load static %}

<div class="container">
    <h1><strong>Zamówienia</strong></h1>
    <br />
    <table>
		<tr>
			<th>Transakcja:</th>
			<th>Kupiec:</th>
			<th>Czas Zakupu:</th>
            <th>Complete:</th>
            <th></th>
		</tr>

		{% for ord in object_list %}
		<tr style="border-bottom: 1px solid lightgrey;">
			<td>
				<a href="{{ ord.get_absolute_url2 }}">{{ord.transaction_id}}</a>
                <br />
                <br />
				<small>Wartość zamówienia: {{ord.get_cart_total_brutto|floatformat:2}}PLN</small>
			</td>
            {% if ord.customer.name %}
    			<td>
    				<p>{{ord.customer.name}}</p>
    			</td>
            {% else %}
                <td>
                    <p>Guest</p>
                </td>
            {% endif %}
            <td>
				<p>{{ord.date_ordered}}</p>
			</td>
            <td>
				<p>{{ord.complete}}</p>
			</td>
            <td>
                <a href="{{ ord.get_absolute_url2 }}" class="btn">Zobacz</a>
            </td>
		</tr>
		{% endfor %}
	</table>
</div>
{% endblock %}

website/dashboard/templates/dashboard/product_form.html
{% extends "dashboard/dashboard-base.html" %}
{% load crispy_forms_tags %}
{% block content %}
{% load static %}

<div class="container">
    <div class="row py-5">
        <div class="col-md-5">
            <div class='content-section'>
                <form method='POST'>
                    {% csrf_token %}
                    <fieldset class='form-group'>
                        <legend class='border-bottom mb-4'>Create Product</legend>
                        {{ form }}
                        <div class='form-group py-3'>
                            <button class='btn btn-outline-dark', type='submit'>Dodaj</button>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
        <div class="col-md-5">
        </div>
    </div>
</div>
{% endblock %}

website/dashboard/templates/dashboard/products.html
{% extends "dashboard/dashboard-base.html" %}
{% block content %}
{% load static %}

<div class="container">
    <h1><strong>Produkty</strong></h1>
    <a class='btn' href="{% url 'dashboard:product-create' %}">Dodaj</a>
	<table>
		<tr>
			<th> </th>
			<th>Nazwa:</th>
			<th>Cena:</th>
            <th></th>
		</tr>
        {% for product in object_list %}
		<tr style="border-bottom: 1px solid lightgrey;">
			<td>
				<a href="{{ product.get_absolute_url }}"><img class="row-image ml-5" style="height:100px; width:100px;" src="{{ product.image1.url }}" ></a>
			</td>
			<td>
				<p>{{product.title}}</p>
                <p>Kod: {{product.slug}}</p>
			</td>
			<td>
				<div class="column">
                    <p>Paczka: {{product.pack}} PLN</p>
					<p>Cena: {{product.price|floatformat:2}} PLN</p>
				</div>
			</td>
            <td>
                <div class="column">
                    <a style="color: blue; margin: 0px 10px" href="">Edytuj</a>
                    <a class="btn" style="background-color:#f42525;" href="">Usuń</a>
                    <a class="btn" href="{{ product.get_absolute_url }}">Zobacz</a>
                </div>
            </td>
		</tr>
		{% endfor %}
		</table>
</div>

{% endblock %}