website/shop/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from user import forms as user_forms

app_name = 'shop'

urlpatterns = [
    path('', views.home, name='home'),
    path('faq/', views.faq, name='faq'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('products/', views.ProductListView.as_view(), name='products'),
    path('product/<slug>/', views.ItemDetailView.as_view(), name='product'),
    path('orders/', views.OrderListView.as_view(), name='orders'),
    path('order/<orderId>/', views.OrderProductsListView.as_view(), name='order'),
    path('cart/', views.cart, name='cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('order_complete/', views.order_complete, name='order_complete'),
    path('add_to_cart/', views.addToCart, name='add_to_cart'),
    path('move_cart/', views.moveItemCarts, name='move_cart'),
    path('process_order/', views.processOrder, name='process_order'),
    path('guest/', auth_views.LoginView.as_view(template_name="shop/guestUserLogin.html", authentication_form=user_forms.UserLoginForm),name='guest'),
    path('shipping_update/', views.shipping_update, name='shipping_update'),
    path('order_confirmation/', views.confirmation, name='order_confirmation'),
    path('profile/', views.profile, name='profile'),
    path('regulamin/', views.regulamin, name='regulamin'),
]

website/website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from user import views as user_views
from user import forms as user_forms

urlpatterns = [
    path('', include('shop.urls', namespace="shop")),
    path('dashboard/', include('dashboard.urls', namespace="dashboard")),
    path('admin/', admin.site.urls),
    path('signup/', user_views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name="user/login.html", authentication_form=user_forms.UserLoginForm),name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='user/logout.html'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='user/password_reset.html', form_class=user_forms.UserPasswordResetForm), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='user/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='user/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='user/password_reset_complete.html'), name='password_reset_complete'),
    path('reset/<uidb64>/<token>/',
         user_views.activate, name='activate'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

website/shop/forms.py
from django import forms
from .models import Customer
from django.contrib.auth.models import User


class ShippingUpdateForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ['phone', 'nip']


class UserUpdateForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'input-box',
            'placeholder': 'nazwa użytkownika',
            }
    ))

    email = forms.CharField(label="E-mail",widget=forms.TextInput(
        attrs={
            'class': 'input-box',
            'placeholder': 'email',
            }
    ))

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileUpdateForm(forms.ModelForm):

    name = forms.CharField(label="Imię",widget=forms.TextInput(
        attrs={
            'class': 'input-box',
            'placeholder': 'imię',
            }
    ))

    surname = forms.CharField(label="Nazwisko", widget=forms.TextInput(
        attrs={
            'class': 'input-box',
            'placeholder': 'nazwisko',
            }
    ))

    phone = forms.CharField(label="Numer telefonu", widget=forms.TextInput(
        attrs={
            'class': 'input-box',
            'placeholder': 'nr telefonu',
            }
    ))

    class Meta:
        model = Customer
        fields = ['name', 'surname', 'phone']

website/shop/views.py
from django.shortcuts import render
from .models import Product, OrderItem, Order, ShippingAddress, Category, Customer, Company
from django.views.generic import ListView, DetailView
from django.contrib.auth.decorators import login_required
from django.db.models import Q
# from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import redirect
from django.contrib import messages as messages
from django.http import JsonResponse
from .forms import ShippingUpdateForm, UserUpdateForm, ProfileUpdateForm
import json
from .utils import cartData
import datetime
from .filters import ProductFilterSet
from django.http import HttpResponse
import decimal
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.core.mail import EmailMessage
from django.utils import timezone
# from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
# Create your views here.


def home(request):
    try:
        data = cartData(request)
        counterCartItems = data['counterCartItems']
        cartItems = data['cartItems']
    except:
        counterCartItems = 0

    # Fix filtering recommended products
    recProdcuts = Product.objects.order_by('price')[:4]
    newProducts1 = Product.objects.order_by('-release_date')[:4]
    newProducts2 = Product.objects.order_by('-release_date')[4:8]
    categories = Category.get_all_categories()

    try:
        best = recProdcuts[0]
        context = {'cartItems': cartItems, 'categories': categories, 'best': best, 'newProducts1': newProducts1, 'newProducts2': newProducts2, 'recProducts': recProdcuts, 'counterCartItems': counterCartItems}
    except:
        context = {'categories': categories, 'newProducts1': newProducts1, 'newProducts2': newProducts2, 'recProducts': recProdcuts, 'counterCartItems': counterCartItems}

    return render(request, 'shop/home.html', context)


class ProductListView(ListView):

    model = Product
    template_name = "shop/products.html"
    paginate_by = 8
    ordering = ['title']

    def get_queryset(self, *args, **kwargs):
        if 'q' in self.request.GET:
            query = self.request.GET['q']
            queryset = product_querySet(query)
            return queryset

        products = None
        categoryID = self.request.GET.get('category')
        if categoryID:
            products = Product.get_all_products_by_categoryid(categoryID)
        else:
            products = Product.get_all_products()

        queryset = ProductFilterSet(self.request.GET, queryset=products).qs
        return queryset

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        cartItems = []
        try:
            data = cartData(self.request)
            counterCartItems = data['counterCartItems']
            cartItems = data['cartItems']
        except:
            counterCartItems = 0

        context['counterCartItems'] = counterCartItems
        context['current_category'] = " "
        categoryID = self.request.GET.get('category')
        if categoryID:
            products = Product.get_all_products_by_categoryid(categoryID)
            context['current_category'] = Category.objects.get(id=categoryID).name
        else:
            products = Product.get_all_products()

        categories = Category.get_all_categories()
        context['categories'] = categories
        context['filter'] = ProductFilterSet(self.request.GET, queryset=products)
        context['cartItems'] = cartItems

        return context


class ItemDetailView(DetailView):
    model = Product
    template_name = "shop/product.html"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        try:
            data = cartData(self.request)
            counterCartItems = data['counterCartItems']
            cartItems = data['cartItems']
            context['cartItems'] = cartItems
        except:
            counterCartItems = 0

        context['counterCartItems'] = counterCartItems
        categoryId = Category.objects.get(name=self.object.category.name)
        recProducts = Product.objects.filter(category=categoryId)
        context['recProducts'] = recProducts[:4]

        return context

# Make the generic Views login_required
class OrderListView(ListView):
    model = Order
    template_name = "shop/order_history.html"
    paginate_by = 10


    def get_queryset(self, *args, **kwargs):
        customer = self.request.user.customer
        queryset = Order.objects.filter(customer=customer, complete=True).order_by('-date_ordered')

        return queryset

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        try:
            data = cartData(self.request)
            counterCartItems = data['counterCartItems']
            cartItems = data['cartItems']
        except:
            counterCartItems = 0

        context['counterCartItems'] = counterCartItems
        context['cartItems'] = cartItems

        return context

class OrderProductsListView(ListView):
    model = OrderItem
    template_name = "shop/orders_products.html"

    def get_context_data(self, *args, **kwargs):

        try:
            data = cartData(self.request)
            counterCartItems = data['counterCartItems']
            cartItems = data['cartItems']
        except:
            counterCartItems = 0

        orderId = self.kwargs['orderId']
        order = Order.objects.get(id=orderId)
        orderItems = OrderItem.objects.filter(order=order)
        context = {'order': order, 'items': orderItems}
        return context


@login_required
def profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, instance=request.user.customer)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Your account has been updated!')
            return redirect('shop:profile')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.customer)

    user = request.user
    context = {
        'u_form': u_form,
        'p_form': p_form,
        'user': user,
    }


    cartItems = []
    try:
        data = cartData(self.request)
        counterCartItems = data['counterCartItems']
        cartItems = data['cartItems']
    except:
        counterCartItems = 0

    context['counterCartItems'] = counterCartItems
    context['cartItems'] = cartItems

    return render(request, "shop/profile.html", context)


def cart(request):
    try:
        data = cartData(request)
        counterCartItems = data['counterCartItems']
        order = data['order']
        items = data['items']
        cartItems = data['cartItems']
        context = {'items': items, 'order': order, 'counterCartItems': counterCartItems, 'cartItems': cartItems}
        return render(request, 'shop/cart.html', context)
    except:
        return render(request, 'shop/cart.html')


def checkout(request):
    try:
        data = cartData(request)
        counterCartItems = data['counterCartItems']
        order = data['order']
        items = data['items']
        cartItems = data['cartItems']
        context = {'items': items, 'order': order, 'counterCartItems': counterCartItems, 'cartItems': cartItems}
        return render(request, 'shop/checkout.html', context)
    except:
        return render(request, 'shop/checkout.html')


def faq(request):
    try:
        data = cartData(request)
        counterCartItems = data['counterCartItems']
        cartItems = data['cartItems']

        context = {'cartItems': cartItems, 'counterCartItems': counterCartItems}
        return render(request, 'shop/FAQ.html', context)
    except:
        return render(request, 'shop/FAQ.html')


def about(request):
    try:
        data = cartData(request)
        counterCartItems = data['counterCartItems']
        cartItems = data['cartItems']

        context = {'cartItems': cartItems, 'counterCartItems': counterCartItems}
        return render(request, 'shop/about.html', context)
    except:
        return render(request, 'shop/about.html')


def contact(request):
    try:
        data = cartData(request)
        counterCartItems = data['counterCartItems']
        cartItems = data['cartItems']
        context = {'cartItems': cartItems, 'counterCartItems': counterCartItems}
        return render(request, 'shop/contact.html', context)
    except:
        return render(request, 'shop/contact.html')


def addToCart(request):
    if request.method == 'GET':
        productId = request.GET['productId']
        action = request.GET['action']
        quantity = int(request.GET['inputVal'])

        try:
            customer = request.user.customer
        except:
            device = request.COOKIES['device']
            customer, created = Customer.objects.get_or_create(device=device)

        product = Product.objects.get(id=productId)
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        orderItem, created = OrderItem.objects.get_or_create(order=order, product=product)

        if action == 'add':
            orderItem.quantity += quantity
            message = "Produkt został dodany do koszyka!"
        # elif action == 'remove':
        #     orderItem.quantity = (orderItem.quantity - orderItem.product.pack)
        #     message = "Produkty zosta!"
        elif action == 'removeAll':
            message = "Produkt został usunięty z twojego koszyka!"
            orderItem.quantity = 0
        elif action == 'update':
            message = "Produkt został zaktualizowany!"
            orderItem.quantity = quantity

        orderItem.save()  # saving it to store in database

        if orderItem.quantity <= 0:

website/shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Wólka Moda</title>

    <link rel="shortcut icon" href="{% static 'images/favicon(1).ico' %}" type="image/x-icon" />
    <link rel="stylesheet" href="{% static 'shop/assets/css/styles.css' %}">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">

    var user = '{{request.user}}'

    function getToken(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = cookies[i].trim();
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    const csrftoken = getToken('csrftoken');

    function getCookie(name) {
	    var cookieValue = null;
	    if (document.cookie && document.cookie !== '') {
	        var cookies = document.cookie.split(';');
	        for (var i = 0; i < cookies.length; i++) {
	            var cookie = cookies[i].trim();
	            // Does this cookie string begin with the name we want?
	            if (cookie.substring(0, name.length + 1) === (name + '=')) {
	                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
	                break;
	            }
	        }
	    }
	    return cookieValue;
	}

	function uuidv4() {
	  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c) {
	    var r = Math.random() * 16 | 0, v = c == 'x' ? r : (r & 0x3 | 0x8);
	    return v.toString(16);
	  });
	}

	var device = getCookie('device');

	if (device == null || device == undefined){
		device = uuidv4()
	}

  document.cookie = 'device=' + device + '; SameSite=Lax;' + ";domain=;path=/";

</script>

<style>
    .sidebar {
      height: 100%;
      width: 0;
      position: fixed;
      z-index: 1;
      top: 0;
      right: 0;
      background-color: #111;
      overflow-x: hidden;
      transition: 0.5s;
      padding-top: 60px;
    }

    .sidebar-btn {
      text-decoration: none;
      font-size: 18px;
      color: #818181;
      display: block;
      transition: 0.3s;
      cursor: pointer;
      text-align: center;
    }

    .sidebar a {
      transition: 0.3s;
      cursor: pointer;
    }

    .sidebar .closebtn {
      position: absolute;
      top: 0;
      right: 25px;
      font-size: 36px;
      margin-left: 50px;
    }

    .content {
        padding: 10px 15px;
    }

    #main {
      transition: margin-left .5s;
      padding: 16px;
      float: right;
    }

    /* On smaller screens, where height is less than 450px, change the style of the sidenav (less padding and a smaller font size) */
    @media screen and (max-height: 450px) {
      .sidebar {padding-top: 15px;}
      /* .sidebar a {font-size: 18px;} */
    }

</style>

</head>
<div class="header">
    <div class="container">
        <div class="navbar">
            <div class="logo">
                <a href="{% url 'shop:home' %}"><img src="{% static 'images/logo.png' %}" width="250px"></a>
            </div>
            <nav>
                <ul id="MenuItems">
                    <li>
                    <form method="get" action="{% url 'shop:products' %}">
                        <label for="search-field"><i class="fa fa-search"></i>
                        <input style="width:300px; font-size: 18px" type="text" class="input-box" name="q" id="id_q" placeholder="Szukaj...">
                    </form>
                    </li>
                    <li><a href="{% url 'shop:home' %}">Home</a></li>
                    <li><a href="{% url 'shop:products' %}">Produkty</a></li>
                    <li><a href="{% url 'shop:about' %}">O nas</a></li>
                    <li><a href="{% url 'shop:contact' %}">Kontakt</a></li>
                    {% if user.is_authenticated %}
                    <li>
                      <div class="dropdown">
                       <button onclick="openDropdown()" class="dropbtn">Konto</button>
                       <div id="myDropdown" class="dropdown-content">
                         <a href="{% url 'shop:profile'%}">Profil</a>
                         <a href="{% url 'shop:orders'%}">Historia Zamówień</a>
                         {% if user.is_superuser %}
                             <a href="{% url 'dashboard:home' %}">Dashboard</a>
                         {% endif %}
                         <a href="{% url 'logout' %}">Wyloguj się</a>
                       </div>
                      </div>
                    </li>
                    {% else %}
                    <li><a href="{% url 'signup' %}">Register</a></li>
                    <li><a href="{% url 'login' %}">Login</a></li>
                    {% endif %}
                    <li>
                      <div id="menu">
                      <a onclick="openNav()" class="openbtn"><img style="cursor: pointer" src="{% static 'images/cart.png' %}" width="30px" height="30px"></a>
                      <div id="mySidebar" class="sidebar">
                        <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">×</a>
                        <a class="btn sidebar-btn" href="{% url 'shop:cart' %}">Przejdź do zapłaty</a>
                        <div class="sidebar-cart">
                          <h3>Twój koszyk: </h3>
                            {% if cartItems %}
                                {% for item in cartItems %}
                                <div class="cartItem">
                                    <div class="row">
                                        <a href="{{ item.product.get_absolute_url }}"><img src="{{ item.product.image1.url }}" width="50px" height="50px"></a>
                                        <div class="column">
                                            <p>{{item.product.title}}</p>
                                            <p>{{item.product.pack}}</p>
                                        </div>
                                    </div>
                                </div>
                                {% endfor %}
                            {% else %}
                        <p>Twók koszyk jest pusty</p>
                            {% endif %}
                        </div>
                      </div>
                      </div>
                    </li>
                </ul>
                <img src="{% static 'images/menu.png' %}" class="menu-icon" onclick="menuToggle()">
            </nav>
        </div>
    </div>
</div>

<body>
    {% block content %}
    {% endblock %}
</body>

<!-- footer  -->
<div class="footer">
    <div class="container">
        <div class="row">
            <div class="footer-col-1">
                <h3>Informacje</h3>
                <ul>
                    <li>Koszt wysyłki</li>
                    <li>Jak zamawiać</li>
                    <li>Pomoc</li>
                    <li>FAQ</li>
                    <li>Polityka Prywatności</li>
                </ul>
            </div>
            <div class="footer-col-1">
                <h3>Moje Konto</h3>
                <ul>
                    <li>Zamówienia</li>
                    <li>Rachunki</li>
                    <li>Adresy</li>
                    <li>Informacje Osobiste</li>
                    <li>Obsługi klienta</li>
                </ul>
            </div>
            <div class="footer-col-1">
                <h3>Informacje o sklepie</h3>
                <ul>
                    <li><a href="tel:+48 886882885">+48 886 882 885</a></li>
                    <li><a href="tel:+48 579239540">+48 579 239 540</a></li>
                    <li><a href="mailto: contact.wolkamoda@gmail.com">contact.wolkamoda@gmail.com</a></li>
                    <li>Facebook: </li>
                    <li>...</li>
                </ul>
            </div>
            <div class="footer-col-1">
                <h3>Dane do przelewu</h3>
                <ul>
                    <li><strong>Firma:</strong>...</li>
                    <li><strong>Adres korespondencji:</strong>...</li>
                    <li><strong>NIP:</strong>...</li>
                    <li><strong>Bank:</strong>...</li>
                    <li><strong>Kod SWIFT banku:</strong>...</li>
                    <li><strong>Nr konta bankowego:</strong>...</li>
                </ul>
            </div>
        </div>
        <p class="copyright">Copyright © 2021 DALOC. All right reserved.</p>
    </div>

</div>

<script type="text/javascript">
    var MenuItems = $("#MenuItems");

    function menuToggle() {
        MenuItems.toggleClass('open');
    }
</script>

<script type="text/javascript">

  function openDropdown() {
    document.getElementById("myDropdown").classList.toggle("show");
    }

    // Close the dropdown menu if the user clicks outside of it
    window.onclick = function(event) {
    if (!event.target.matches('.dropbtn')) {
      var dropdowns = document.getElementsByClassName("dropdown-content");
      var i;
      for (i = 0; i < dropdowns.length; i++) {
        var openDropdown = dropdowns[i];
        if (openDropdown.classList.contains('show')) {
          openDropdown.classList.remove('show');
        }
      }
    }
  }

  setTimeout(function(){
    if ($('#msg').length > 0) {
      $('#msg').remove();
    }
  }, 2000)

</script>

<script>
  function openNav() {
    document.getElementById("mySidebar").style.width = "300px";
    // document.getElementById("main").style.marginLeft = "300px";
  }

  function closeNav() {
    document.getElementById("mySidebar").style.width = "0";
    // document.getElementById("main").style.marginLeft= "0";
  }
</script>
</html>

website/shop/templates/shop/cart.html
{% extends 'shop/base.html' %}
{% load static %}
{% block content %}

<div class="small-container" style="margin-bottom: 500px">
	<div class="row">
		<div class="col-2">
			<a class="btn" href="{% url 'shop:products' %}">&#x2190; Kontynuuj zakupy</a>
		</div>
		<div class="col-2">
			<a onclick="checkout()" style="float: right" class="btn">Zapłać</a>
		</div>
	</div>
	<table>
		<tr>
			<th>Produkt:</th>
			<th>Ilość:</th>
			<th>W sumie:</th>
		</tr>
		{% if items %}
		{% for item in items %}
			<tr id="product{{item.product.id}}">
				<td>
					<a href="{{ item.product.get_absolute_url }}"><img src="{{ item.product.image1.url }}" ></a>
					<div>
						<p>{{item.product.title}}</p>
						<small>Cena: {{item.product.price}}PLN</small>
						<br/>
						<a data-productId="{{ item.product.id }}" data-action="removeAll" class="remove-item-from-cart a-btn">Usuń</a>
					</div>
				</td>
				<td>
					<div class="plus-minus-input">
						<span class="minus" data-action="remove" data-pack={{ item.product.pack }}>&#8722;</span>
						<input class="quantity" type="number" id="{{item.product.id}}" value="{{item.quantity}}"/>
						<span class="plus" data-action="add" data-pack={{ item.product.pack }}>&#43;</span>
						<span class="update-cart check" data-pack={{ item.product.pack }} data-action="update" data-productId="{{ item.product.id }}">&#10004;</span>
					</div>
				</td>
				<td>
					<div class="column">
						<p>Cena netto: {{item.get_total|floatformat:2}} PLN</p>
						<p>Vat: {{item.get_vat|floatformat:2}} PLN</p>
						<p>Cena brutto: {{item.get_brutto|floatformat:2}} PLN</p>
					</div>
				</td>
			</tr>
			{% endfor %}
		</table>
		{% else %}
		<center>
				<div class="container" style="margin-top: 50px;">
					<div class="info">
						<h2 class="card-title">
							Brak produktów
						</h2>
						<p class="card-text">Twój koszyk wciąż jest pusty.</p>
					</div>
				</div>
		</center>
		{% endif %}

	<div class="total-price">
		<table>
			<tr>
				<td>Razem</td>
				<td>{{order.get_cart_total}} PLN</td>
			</tr>
			<tr>
				<td>Podatek</td>
				<td>{{order.get_cart_total_vat|floatformat:2}} PLN</td>
			</tr>
			<tr>
				<td>W sumie</td>
				<td>{{order.get_cart_total_brutto|floatformat:2}} PLN</td>
			</tr>
		</table>
	</div>
</div>

<script type="text/javascript">

	var minusBtns = document.getElementsByClassName("minus");

	for (var i = 0; i < minusBtns.length; i++){
		minusBtns[i].addEventListener("click", function(e) {
			var pack = parseInt(this.dataset.pack);

			var $input = $(this).parent().find('input');
			var count = parseInt($input.val()) - pack;
			count = count < 1 ? 0 : count;
			$input.val(count);
			$input.change();
			return false;
		});
	}

	var plusBtns = document.getElementsByClassName("plus");

	for (var i = 0; i < minusBtns.length; i++){
		plusBtns[i].addEventListener("click", function(e) {
			var pack = parseInt(this.dataset.pack);

			var $input = $(this).parent().find('input');
			var count = parseInt($input.val()) + pack;
			count = count < 1 ? 1 : count;
			$input.val(count);
			$input.change();
			return false;
		});
	}

	checkBtns = document.getElementsByClassName("update-cart");

	for (var i = 0; i < checkBtns.length; i++){
		$(checkBtns[i]).click(function() {
			var productId = $(this).attr("data-productId");
			var action = $(this).attr("data-action");
			var pack = parseInt(this.dataset.pack);

			// const inputVal = parseInt( $(this).siblings('.quantity').val());

			var inputVal = parseInt( $(this).siblings('.quantity').val());
			if (inputVal%pack != 0){
					inputVal += pack - inputVal%pack
			}

			var url = '/add_to_cart/'
			$.ajax(
			{
				type:'GET',
				url: url,
				data:{
					 productId: productId,
					 action: action,
					 inputVal: inputVal,
				},
				success: function( data )
				{
					toastr.success('Produkt został zaaktualizwany!');
					$('#product'+productId).remove();
				}
			})
		})
	};

	$('.remove-item-from-cart').click(function(){
		var productId = $(this).attr("data-productId");

		var url = '/add_to_cart/'
		$.ajax(
		{
			type:'GET',
			url: url,
			data:{
				 productId: productId,
				 action: 'removeAll',
				 inputVal: 0,
			},
			success: function( data )
			{
				toastr.error('Produkt został usunięty!');
				$('#product'+productId).remove();
			}
		})
	});


	function checkout() {
		counterCartItems = '{{counterCartItems}}'
		console.log(counterCartItems)
		if (counterCartItems == '0'){
			alert("Twój koszyk jest pusty.");
		}
		else{
			user = '{{ user.is_authenticated }}'
			if (user == 'True'){
				window.location.href = "{% url 'shop:checkout' %}"
			}
			else{
				window.location.href = "{% url 'shop:guest' %}"
			}
		}
	}
</script>


{% endblock content %}